version: 2.1
orbs:
  lambda-tunnel: lambdatest/lambda-tunnel@volatile
workflows:
  browser_tests:
    jobs:
      - lambdatest/with_tunnel:
          name: Chrome test
          tunnel_name: chrome
          lambdatest_email: user@lambdatest.com
          steps:
            - run:
                command: |
                  npm install
                  export LAMBDATEST_USERNAME=user
                  node_modules/.bin/nightwatch -e chrome
      - lambdatest/with_tunnel:
          name: Firefox test
          tunnel_name: firefox
          lambdatest_email: user@lambdatest.com
          steps:
            - run:
                command: |
                  npm install
                  export LAMBDATEST_USERNAME=user
                  node_modules/.bin/nightwatch -e firefox
